name: Setup environment
description: Setup environment

runs:
  using: "composite"
  steps:
    - name: install pnpm
      if: inputs.with-pnpm != 'true'
      shell: bash
      run: npm i -g pnpm@9

